// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Phoneno   string           `json:"phoneno"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Order struct {
	ID          string           `json:"id"`
	CustomerID  string           `json:"customer_id"`
	OrderStatus *string          `json:"order_status"`
	OrderDate   pgtype.Timestamp `json:"order_date"`
	TotalPrice  string	  		 `json:"total_price"`
}

type OrderItem struct {
	ID        string           `json:"id"`
	OrderID   string           `json:"order_id"`
	ProductID string           `json:"product_id"`
	Quantity  int32            `json:"quantity"`
	Price     pgtype.Numeric   `json:"price"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Product struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Price     pgtype.Numeric   `json:"price"`
	Stock     int32            `json:"stock"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
